openapi: 3.0.4
info:
  title: Language Detector
  description: >-
    Language Detector is a simple tool for detecting the language of a text. It
    returns the language code and the confidence level.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.0
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
  - url: https://api.apiverve.com/
paths:
  /v1/languagedetector:
    post:
      summary: Detect Language
      description: Detect the language of a body of text
      operationId: languagedetector
      parameters: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: object
                    description: data
              example:
                status: ok
                error: null
                data:
                  - language: spanish
                    confidence: 0.38471794871794873
                    code: es
                  - language: portuguese
                    confidence: 0.2946153846153846
                    code: pt
                  - language: danish
                    confidence: 0.2464615384615384
                    code: da
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occurred, try again later
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: The text to detect the language of
              required:
                - text
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - api_key: []
sampleRequest:
  text: esta es una frase en español. esta API puede detectar fácilmente el idioma
